name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update GitHub Streak Stats in README
        run: |
          curl -o ./README.md "https://streak-stats.demolab.com?user=webwithaman&theme=black-ice&hide_border=true&ring=f97316&fire=f97316&currStreakNum=ffffff&currStreakLabel=f97316&sideNums=ffffff&sideLabels=ffffff&dates=ffffff&token=${{ secrets.GH_PAT }}"

      - name: Commit Changes
        run: |
          git config --local user.name "GitHub Actions"
