name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update GitHub Streak Stats in README
        run: |
          # Define the streak image URL
          STREAK_IMAGE_URL="https://streak-stats.demolab.com?user=webwithaman&theme=black-ice&hide_border=true&ring=f97316&fire=f97316&currStreakNum=ffffff&currStreakLabel=f97316&sideNums=ffffff&sideLabels=ffffff&dates=ffffff"

          # Use 'sed' to replace the second <img> tag in your README.md file with the updated streak image URL
          sed -i '0,/<a href="http:\/\/www.github.com\/webwithaman"><img src=".*" \/>/s||<a href="http:\/\/www.github.com\/webwithaman"><img src="'"$STREAK_IMAGE_URL"'" \/>|' README.md

      - name: Commit Changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Update GitHub Streak Stats"
          git push
