name: Update GitHub Profile README with Streak Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch GitHub Streak Stats and Update README
        run: |
          curl -o ./README.md "https://streak-stats.demolab.com?user=webwithaman&theme=black-ice&hide_border=true&ring=f97316&fire=f97316&currStreakNum=ffffff&currStreakLabel=f97316&sideNums=ffffff&sideLabels=ffffff&dates=ffffff&token=${{ secrets.GH_PAT }}"

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit Changes
        run: |
          git add README.md
          git commit -m "Update GitHub Streak Stats in README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
